Feature/provider
nfqakademija/tech-guide pull request #13
Opened 2018-04-22 13:57 UTC by MatasSilinskas

2018-04-22 20:58 UTC, sergejvoronov requested changes

2018-04-22 20:58 UTC, sergejvoronov commented on src/DataFixtures/ORM/AnswerProvider.php
>          return array_values($this->answers)[$answer_num - 1];
naudojam camelCase :) pakeisk visur

2018-04-23 08:30 UTC, sergejvoronov commented
kai sutvarkysi, paprasyk Martyno paaproovint ir sumerginkit :) as sian turbut jau nebusiu online :)

2018-04-23 12:20 UTC, MartynasDru submitted a review, later dismissed

2018-04-23 12:23 UTC, MartynasDru approved these changes

2018-04-23 12:25 UTC, merged